name: Build on linux
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [clang, gcc]
        build_type: [Debug, Release]
        include:
          - compiler: clang
            cc: clang
            cxx: clang++
          - compiler: gcc
            cc: gcc
            cxx: g++
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build bison flex libfl2 libfl-dev
      - uses: actions/checkout@v2
      - name: configure
        run: |
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja .
      - name: build
        run: cmake --build build --target all
      - name: Run Test
        run: cd build && ctest -V
