name: Build on Windows
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        compiler: [clang]
        build_type: [debug, release]
        include:
          - compiler: clang
            cc: clang.exe
            cxx: clang++.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install tools
        run: choco install -y ninja
      - uses: actions/checkout@v3
      - name: configure
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: cmake --preset ${{ matrix.build_type }}
      - name: build
        run: cmake --build --preset ${{ matrix.build_type }}
      - name: test
        run: ctest --preset ${{ matrix.build_type }} -VV
