name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y ninja-build clang libclang-dev
      - uses: actions/checkout@v2
      - name: configure
        run: "CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage ."
      - name: build
        run: cmake --build build --target all
      - name: Run Test
        run: cd build && ctest -V

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upload code coverage to coveralls
        if: contains(matrix.os, 'ubuntu')
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools cpp-coveralls
          coveralls -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*test/.*.c.*" --exclude "venv" --exclude "build/_deps" 
