name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y ninja-build clang libclang-dev
      - uses: actions/checkout@v2
      - name: configure
        run: "CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja ."
      - name: build
        run: cmake --build build --target all
      - name: Run Test
        run: cd build && ctest -V
